version: 2
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  metrics:
    enabled: true
  coverage:
    enabled: true
  tools:
    - name: eslint
      enabled: true
    - name: trivy
      enabled: true
exclude_paths:
  - 'node_modules/**'
  - '.git/**'
  - '*.test.js'