[[headers]]
  for = "/*"
  [headers.values]
    # A more permissive CSP as a starting point
    Content-Security-Policy = "script-src 'self' https://www.googletagmanager.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; object-src 'none'; base-uri 'self';"
    # Add other directives like style-src, img-src, font-src etc. as needed based on browser console errors