[[headers]]
  for = "/*"
  [headers.values]
    # Updated CSP to allow connections to reCAPTCHA and Supabase
    Content-Security-Policy = "script-src 'self' https://www.googletagmanager.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://unpkg.com https://cdn.jsdelivr.net/npm/ 'unsafe-inline'; object-src 'none'; base-uri 'self'; connect-src 'self' https://www.google.com/recaptcha/ https://uzgxluiqyovpkyjpqles.supabase.co;"
    # Add other directives like style-src, img-src, font-src etc. as needed based on browser console errors